In [39]:

import os
import pandas as pd
import numpy as np
import natsort
import scipy
import math
import librosa
import librosa.display
import tensorflow as tf
import matplotlib.pyplot as plt


In [40]:
main_folder_path = "/media/yash/New Volume/data/short data"
i=0
for folder_name in os.listdir(main_folder_path):
    folder_path = os.path.join(main_folder_path, folder_name)
    if os.path.isdir(folder_path):
        for filename in os.listdir(folder_path):
            new_filename = f"{i}.ogg"
            i+=1
            current_file_path = os.path.join(folder_path, filename)
            new_file_path = os.path.join(folder_path, new_filename)
            os.rename(current_file_path, new_file_path)

In [41]:
data = []
for folder_name in os.listdir(main_folder_path):
    folder_path = os.path.join(main_folder_path, folder_name)
    if os.path.isdir(folder_path):
        files = os.listdir(folder_path)
        for file in files:
            data.append({'File': file, 'Folder':folder_name})

In [42]:
print(data)

[{'File': '0.ogg', 'Folder': 'acafly'}, {'File': '1.ogg', 'Folder': 'acafly'}, {'File': '10.ogg', 'Folder': 'acafly'}, {'File': '100.ogg', 'Folder': 'acafly'}, {'File': '101.ogg', 'Folder': 'acafly'}, {'File': '102.ogg', 'Folder': 'acafly'}, {'File': '103.ogg', 'Folder': 'acafly'}, {'File': '104.ogg', 'Folder': 'acafly'}, {'File': '105.ogg', 'Folder': 'acafly'}, {'File': '106.ogg', 'Folder': 'acafly'}, {'File': '107.ogg', 'Folder': 'acafly'}, {'File': '108.ogg', 'Folder': 'acafly'}, {'File': '109.ogg', 'Folder': 'acafly'}, {'File': '110.ogg', 'Folder': 'acafly'}, {'File': '111.ogg', 'Folder': 'acafly'}, {'File': '112.ogg', 'Folder': 'acafly'}, {'File': '113.ogg', 'Folder': 'acafly'}, {'File': '114.ogg', 'Folder': 'acafly'}, {'File': '115.ogg', 'Folder': 'acafly'}, {'File': '116.ogg', 'Folder': 'acafly'}, {'File': '117.ogg', 'Folder': 'acafly'}, {'File': '118.ogg', 'Folder': 'acafly'}, {'File': '119.ogg', 'Folder': 'acafly'}, {'File': '120.ogg', 'Folder': 'acafly'}, {'File': '121.ogg', 

In [43]:
df = pd.DataFrame(data)

In [44]:
len(df)

1663

In [45]:
df['Folder'].unique()

array(['acafly', 'acowoo', 'aldfly', 'ameavo', 'amecro', 'amegfi',
       'amekes', 'amepip', 'amered', 'amerob'], dtype=object)

In [46]:
encoded_df = pd.get_dummies(df, columns=['Folder'])

In [47]:
encoded_df.head()

File  Folder_acafly  Folder_acowoo  Folder_aldfly  Folder_ameavo  \
0    0.ogg              1              0              0              0   
1    1.ogg              1              0              0              0   
2   10.ogg              1              0              0              0   
3  100.ogg              1              0              0              0   
4  101.ogg              1              0              0              0   

   Folder_amecro  Folder_amegfi  Folder_amekes  Folder_amepip  Folder_amered  \
0              0              0              0              0              0   
1              0              0              0              0              0   
2              0              0              0              0              0   
3              0              0              0              0              0   
4              0              0              0              0              0   

   Folder_amerob  
0              0  
1              0  
2              0  
3              0  
4              0

In [48]:
sampleAll = {}
for folder_name in os.listdir(main_folder_path):
    folder_path = os.path.join(main_folder_path, folder_name)
    if os.path.isdir(folder_path):
        for file in os.listdir(folder_path):
            file_path = os.path.join(folder_path, file)
            if os.path.isfile(file_path):
                audio, sr = librosa.load(file_path)
                sampleAll[file] = audio
                

KeyError: 1

In [53]:
allFeature = {}
for folder_name in os.listdir(main_folder_path):
    folder_path = os.path.join(main_folder_path, folder_name)
    if os.path.isdir(folder_path):
        for file in os.listdir(folder_path):
            file_path = os.path.join(folder_path, file)
            if os.path.isfile(file_path):
              OneSample = sampleAll[file]
              # Energy
              energy=np.sum(np.square(OneSample)).reshape(-1,1)
              print("**********Energy***************")
              print(energy)
              # Spectral Centroid
              spectral_centroid = librosa.feature.spectral_centroid(y=OneSample, sr=sr,n_fft=20, hop_length=len(OneSample)+1, center = False, win_length = 15 )
              print("**********Spectral Centroid***************")
              print(spectral_centroid)
              #RMS
              rms = librosa.feature.rms(y=OneSample, hop_length=len(OneSample)+1)
              print("**********RMS***************")
              print(rms)

              featuresOneFrame=np.concatenate((energy, spectral_centroid, rms),axis = 0)
              print("**********One Frame***************")
              print(featuresOneFrame)
              allFeature[file]= featuresOneFrame

**********Energy***************
[[6256.774]]
**********Spectral Centroid***************
[[5573.0238779]]
**********RMS***************
[[0.01715617]]
**********One Frame***************
[[6.25677393e+03]
 [5.57302388e+03]
 [1.71561744e-02]]
**********Energy***************
[[9556.304]]
**********Spectral Centroid***************
[[5896.94742397]]
**********RMS***************
[[0.10210726]]
**********One Frame***************
[[9.55630371e+03]
 [5.89694742e+03]
 [1.02107264e-01]]
**********Energy***************
[[765.7417]]
**********Spectral Centroid***************
[[4938.08783418]]
**********RMS***************
[[0.00417623]]
**********One Frame***************
[[7.65741699e+02]
 [4.93808783e+03]
 [4.17623483e-03]]
**********Energy***************
[[1.4730047]]
**********Spectral Centroid***************
[[4366.71405314]]
**********RMS***************
[[0.00093078]]
**********One Frame***************
[[1.47300470e+00]
 [4.36671405e+03]
 [9.30783048e-04]]
**********Energy***************
[[125.08